// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers/Providers";
import { Toaster } from "react-hot-toast"; // ← أضف هذا

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrap your children in the client-only Providers component */}
        <Providers>
          {children}
          {/* إضافة Toaster هنا */}
          <Toaster
            position="top-center"
            toastOptions={{
              duration: 2000,
              style: {
                fontSize: "14px",
                padding: "8px 16px",
                fontFamily: "geist Mono",
              },
            }}
          />
        </Providers>
      </body>
    </html>
  );
}
